# Generated by Django 6.0.1 on 2026-01-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, only approved followers can see your content.",
                verbose_name="Private Profile",
            ),
        ),
    ]
