# Generated by Django 6.0.1 on 2026-01-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("APPROVED", "Aprovado"),
                    ("REJECTED", "Rejeitado"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
