# Generated by Django 6.0.1 on 2026-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("phone", "Phone"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
