# Generated by Django 6.0.1 on 2026-02-04 12:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="media",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="posts_media/",
                validators=[], # Cleaned!
            ),
        ),
    ]