# Generated by Django 6.0.1 on 2026-02-04 13:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_post_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=accounts.models.get_post_media_path,
                validators=[], # I removed the broken function here
            ),
        ),
    ]