# Generated by Django 6.0.1 on 2026-02-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("APPROVED", "Aprovado"),
                    ("REJECTED", "Rejeitado"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
