# Generated by Django 6.0.1 on 2026-02-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_post_moderation_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_private",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
