# Generated by Django 6.0.1 on 2026-02-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_user_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="unfollowed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
