# Generated by Django 6.0.1 on 2026-02-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="media_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
