# Generated by Django 6.0.1 on 2026-02-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_comment_media_url_alter_comment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comment_images/"),
        ),
    ]
