# Generated by Django 6.0.1 on 2026-02-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_report"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("reporter", "post")},
        ),
    ]
