# Generated by Django 6.0.1 on 2026-02-22 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_alter_report_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("FOLLOW", "Novo Seguidor"),
                    ("LIKE", "Novo Gosto"),
                    ("COMMENT", "Novo Comentário"),
                    ("REPORT_UPDATE", "Atualização de Denúncia"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
