# Generated by Django 6.0.1 on 2026-02-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_notification_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="stored_post_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
