# Generated by Django 6.0.1 on 2026-02-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_notification_stored_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ban_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
