# Generated by Django 6.0.1 on 2026-03-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_user_ban_reason_user_is_banned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="image_status",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="profile",
            name="image_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("APPROVED", "Aprovado"),
                    ("REJECTED", "Rejeitado"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
