# Generated by Django 6.0.1 on 2026-03-03 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_remove_user_bio_remove_user_image_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                related_name="followers",
                through="accounts.Follow",
                through_fields=("follower", "following"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["follower", "following"], name="accounts_fo_followe_852c4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["unfollowed_at"], name="accounts_fo_unfollo_a888af_idx"
            ),
        ),
    ]
