# Generated by Django 6.0.1 on 2026-06-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_add_follow_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("local", "Local"),
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("phone", "Phone"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
