# Generated by Django 6.0.1 on 2026-06-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_alter_user_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="provider",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("phone", "Phone"),
                ],
                default="local",
                max_length=20,
            ),
        ),
    ]
