[mypy]
python_version = 3.12
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

# Configurações de rigor
strict = False
strict_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
disallow_any_generics = True
check_untyped_defs = True
ignore_missing_imports = True
# Desative a exigência de tipagem em tudo que é função
disallow_untyped_defs = False
disallow_incomplete_defs = False

# Equivale ao exclude do pyproject
exclude = (migrations/|venv/|.venv/|tests/)

[mypy.plugins.django-stubs]
django_settings_module = "config.settings"

# Ignorar erros em arquivos específicos
[mypy-*.migrations.*]
ignore_errors = True

[mypy-manage]
ignore_errors = True